/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "Arduino_menu.h"
#include "ThemeCoolBlueTraditional.h"

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "tc_menu_test_2", "b57bfc63-3dfc-447d-846e-3841e3abd3ce" };

//Adafruit_ILI9341 gfx(27, -1, 12, 14, 25);
Adafruit_ILI9341 gfx(5, 26, 25); // HW SPI

AdafruitDrawable gfxDrawable(&gfx, 0);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &gfxDrawable);

// Global Menu Item declarations
RENDERING_CALLBACK_NAME_INVOKE(fnSubMenu2NewTextItemRtCall, textItemRenderFn, "New TextItem", -1, NO_CALLBACK)
TextMenuItem menuSubMenu2NewTextItem(fnSubMenu2NewTextItemRtCall, "", 5, 5, NULL);
const PROGMEM SubMenuInfo minfoSubMenu2 = { "SubMenu 2", 4, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackSubMenu2(&minfoSubMenu2, &menuSubMenu2NewTextItem, INFO_LOCATION_PGM);
SubMenuItem menuSubMenu2(&minfoSubMenu2, &menuBackSubMenu2, NULL, INFO_LOCATION_PGM);
const PROGMEM BooleanMenuInfo minfoSubMenu1NewBoolItem = { "New BoolItem", 6, 0xffff, 1, NO_CALLBACK, NAMING_TRUE_FALSE };
BooleanMenuItem menuSubMenu1NewBoolItem(&minfoSubMenu1NewBoolItem, false, NULL, INFO_LOCATION_PGM);
RENDERING_CALLBACK_NAME_INVOKE(fnSubMenu1NumberRtCall, largeNumItemRenderFn, " Number", -1, NO_CALLBACK)
EditableLargeNumberMenuItem menuSubMenu1Number(fnSubMenu1NumberRtCall, LargeFixedNumber(12, 4, 0U, 0U, false), 3, true, &menuSubMenu1NewBoolItem);
const PROGMEM SubMenuInfo minfoSubMenu1 = { "SubMenu1", 1, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackSubMenu1(&minfoSubMenu1, &menuSubMenu1Number, INFO_LOCATION_PGM);
SubMenuItem menuSubMenu1(&minfoSubMenu1, &menuBackSubMenu1, &menuSubMenu2, INFO_LOCATION_PGM);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setSizeBasedEEPROMStorageEnabled(false);
    // Code generated by plugins.
    gfx.begin(80000000);
    gfx.setRotation(3);
    renderer.setUpdatesPerSecond(5);
    switches.init(internalDigitalIo(), SWITCHES_POLL_EVERYTHING, true);
    menuMgr.initForEncoder(&renderer, &menuSubMenu1, 0, 2, 21);
    renderer.setTitleMode(BaseGraphicalRenderer::TITLE_FIRST_ROW);
    renderer.setUseSliderForAnalog(true);
    installCoolBlueTraditionalTheme(renderer, MenuFontDef(nullptr, 1), MenuFontDef(nullptr, 1), true);
}

